
package com.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWs", targetNamespace = "http://service.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWs {


    /**
     * 
     * @return
     *     returns java.util.List<com.service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service.com/", className = "com.service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service.com/", className = "com.service.GetComptesResponse")
    @Action(input = "http://service.com/BanqueWs/getComptesRequest", output = "http://service.com/BanqueWs/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param code
     * @return
     *     returns com.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service.com/", className = "com.service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service.com/", className = "com.service.GetCompteResponse")
    @Action(input = "http://service.com/BanqueWs/getCompteRequest", output = "http://service.com/BanqueWs/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConversionEutoToDh")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConversionEutoToDh", targetNamespace = "http://service.com/", className = "com.service.ConversionEutoToDh")
    @ResponseWrapper(localName = "ConversionEutoToDhResponse", targetNamespace = "http://service.com/", className = "com.service.ConversionEutoToDhResponse")
    @Action(input = "http://service.com/BanqueWs/ConversionEutoToDhRequest", output = "http://service.com/BanqueWs/ConversionEutoToDhResponse")
    public double conversionEutoToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

}
